name: Deploy Dev
on: 
  workflow_dispatch:

# Add permission to allow 
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          ref: dev
          submodules: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::990864464737:role/GithubActionsRole
          aws-region: us-east-1

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Packages
        run: npm install

      - name: Synth stack
        run: npx cdk synth

      - name: Deploy stack
        run: npx cdk deploy dev-us-east-1-Backend
